spring:
  threads:
    virtual:
      enabled: false

  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://mongo:27017/postservice}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

server:
  servlet:
    context-path: /api
  port: 8081

logging:
  level:
    org.springframework.data.mongodb: DEBUG

user-service:
  url: ${USER_SERVICE_URL:http://localhost:8080/api}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,configprops
