basePath: /
definitions:
  dto.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  dto.FeedResponse:
    properties:
      limit:
        type: integer
      page:
        type: integer
      posts:
        items:
          $ref: '#/definitions/dto.PostResponse'
        type: array
      userId:
        type: string
    type: object
  dto.PostResponse:
    properties:
      caption:
        type: string
      commentCount:
        type: integer
      createdAt:
        type: string
      id:
        type: string
      imageUrl:
        type: string
      likeCount:
        type: integer
      userId:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Feed Service do AstreiaGram, entrega funcionalidades relacionadas ao
    feed para a aplicação.
  title: AstreiaGram Feed Service API
  version: "1.0"
paths:
  /api/feed/{userId}:
    get:
      description: Retorna posts de um feed de algum usuário.
      parameters:
      - description: ID do usuário
        in: path
        name: userId
        required: true
        type: string
      - default: 1
        description: Número da página
        in: query
        name: page
        type: integer
      - default: 50
        description: Número de posts por página
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.FeedResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Procura por um feed.
swagger: "2.0"
