name: Deploy Contínuo (CD) Local

on:
  push:
    branches: [ feature/ansible-pipeline-automatizado ]

jobs:
  run-ansible-deploy:
    runs-on: self-hosted # Diz ao GitHub para usar a sua VM

    steps:
    - name: Atualizar código fonte na VM
      uses: actions/checkout@v4

    - name: Executar o Ansible Playbook localmente
      run: |
        cd infra-devops/ansible
        ansible-playbook -i inventory playbook.yml -c local
